Big refactoring
airalab/sensors-connectivity pull request #69
Opened 2023-01-31 14:40 UTC by tubleronchik

2023-02-04 07:26 UTC, Vourhey approved these changes

2023-02-14 15:59 UTC, PaTara43 requested changes
глобально - добавь везде документацию, втч с описанием параметров входных, могу предложить еще прогнать все сначала isort, а потом black. Страктура теперь понятнее, все по папочкам, круто!

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/drivers/sds011.py
> +from ...constants import MOBILE_GPS
круто, что все в константах :+1:

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/drivers/sds011.py
> -SDS011_MODEL = 2  # unique model for the driver
по 118 строке - я так понимаю, это взят откуда-то еще, просто сейчас самый массовый для питона докстринг формат - reStructured text, а если добавлять типизацию переменных в ах указание в функции, то не нужно будет этого делать в докстринге

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/feeders/datalog_feeder.py
>  def _sort_payload(data: dict) -> dict:
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/feeders/datalog_feeder.py
>  def _sort_payload(data: dict) -> dict:
строка 47

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/config/default.json
>     "luftdaten": {
ты ее везде выпилила.. или нет?

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/feeders/frontier_datalog.py
>      def __init__(self, config: dict) -> None:
а что вообще за feeder Frontier? в старую сетку шоль?

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/feeders/robonomics_feeder.py
> +def _to_pubsub_message(data: dict) -> str:
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/feeders/robonomics_feeder.py
> +def _to_ping_message(data: dict) -> str:
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/feeders/robonomics_feeder.py
> +    def feed(self, data: tp.List[dict]) -> None:
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/feeders/robonomics_feeder.py
>      return json.dumps(message)
мб класс RobonomicsFeeder назвать как-то типа IPFSPubSubFeeder? Ибо есть свой пабсаб у робономики и это не он

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/base.py
> +    def __post_init__(self) -> None:
доки, даже тут)))

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/base.py
> +class Device:
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/base.py
> +    def generate_pubkey(self, id: str) -> str:
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/environmental_box.py
> +@dataclass(repr=False, eq=False)
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/environmental_box.py
> +    def __post_init__(self) -> None:
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/environmental_box.py
> +    def _SDS011_values_saver(self, meas: dict, value: dict) -> dict:
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/mobile_lab.py
> +class MobileLab(Device):
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/mobile_lab.py
> +    def __post_init__(self) -> None:
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/mobile_lab.py
> +    def _mobile_sensor_data_saver(self, meas: dict, value: str) -> dict:
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/sensor_sds011.py
> +class SensorSDS011(Device):
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/sensor_sds011.py
> +
переборщила с абзацами)

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/sensor_sds011.py
> +    def __post_init__(self) -> None:
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/trackagro_sensor.py
> +from connectivity.config.logging import LOGGING_CONFIG
подтягивает отсюда?... не нужны ... ?

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/trackagro_sensor.py
> +class TrackAgro(Device):
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/trackagro_sensor.py
> +    def __post_init__(self) -> None:
доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/trackagro_sensor.py
> +from connectivity.config.logging import LOGGING_CONFIG
и почему вообще именованные логи именно тут?

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/sensors/trackagro_sensor.py
> +    def __post_init__(self) -> None:
и далее по файлу

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/stations/comstation.py
>  import threading
доки можн даже сюда, описывать что тут вообще происходит и что такоее comstation

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/stations/comstation.py
> +        # timestamp = int(time.time())
если не надо -убери)

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/stations/comstation.py
> +        # super().__init__(config)
аналогично, раз уже льешь в мейн - надо почистить

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/stations/comstation.py
>  import threading
и да, по всему файлы - доки, доки, сука, доки

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/stations/httpstation.py
>  # -*- coding: utf-8 -*-
аналогично comstation

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/stations/httpstation.py
> +        # super().__init__(config)
аналогично, надо чистить

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/stations/istation.py
>  # This is an interface for a station
АНалогично comstation

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/stations/mqttstation.py
>  import paho.mqtt.client as mqtt
аналогично comstation

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/stations/mqttstation.py
> -                temperature = None
чет не увидел, куда оно все уехало...

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/stations/trackargostation.py
> +        # super().__init__(config)
убрать

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/src/stations/trackargostation.py
>  import ssl
аналогично comstation

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/utils/generate_pubkey.py
> +def generate_pubkey(id: str) -> str:
доки, этого не было уже в sensors/base?

2023-02-14 15:59 UTC, PaTara43 commented on connectivity/utils/get_mac.py
> +def _get_mac() -> str:
доки

2023-02-14 16:39 UTC, tubleronchik commented on connectivity/main.py
>      FrontierFeeder,
ну в функции` _populate_stations` s это вполне логично, но я учту. Такое наименование исторически сложилось))

2023-02-14 16:43 UTC, tubleronchik commented on README.md
> +## Development
Жду обновления на академии)

2023-02-14 16:52 UTC, tubleronchik commented on connectivity/src/feeders/datalog_feeder.py
я не оч шарю, делала по примеру Макара. А какой стейт тут может быть?

2023-02-14 16:59 UTC, tubleronchik commented on connectivity/src/stations/mqttstation.py
> -                temperature = None
там создается инстанс класса определенного датчика. все ок. смотри /sensors

2023-02-14 17:04 UTC, tubleronchik commented on connectivity/src/feeders/datalog_feeder.py
>      for m in buf:
одно измерение с одного датчика

2023-02-14 17:05 UTC, tubleronchik commented on connectivity/src/feeders/datalog_feeder.py
>      with ipfshttpclient.connect(endpoint) as client:
хочу, в планах через одно обновление (следующее уже написано, и оно о другом)

2023-02-14 17:07 UTC, tubleronchik commented on connectivity/src/feeders/datalog_feeder.py
>          if self.config["datalog"]["enable"]:
Эта функция вызывается в треде в main.py, как и все функции из всех фидеров. Надо подумать о такой же проверке в мейне, как для станций.

2023-02-14 17:12 UTC, tubleronchik commented on connectivity/src/feeders/datalog_feeder.py
>      with ipfshttpclient.connect(endpoint) as client:
хочу, в следующей версии) мне надо основательно тестить все, прежде чем накатывать обновы на серваки. А

2023-02-14 17:13 UTC, tubleronchik commented on connectivity/config/default.json
>     "luftdaten": {
fixed)

2023-02-15 11:01 UTC, tubleronchik commented on connectivity/src/feeders/frontier_datalog.py
>      def __init__(self, config: dict) -> None:
Не, это было для нагрузки сети, помнишь? В даталог станции отправляется хэш от файла раз в 10 минут, а фронтир отправляет строку данных в каждый блок

2023-02-19 18:33 UTC, merged